Minor refactoring

diff --git a/kleber b/kleber
--- a/kleber
+++ b/kleber
@@ -8,14 +8,16 @@
 # --
 set -e
 ARGS="$*"
-VERSION="0.7.2"
+VERSION="0.7.3"
 KLEBER_URL="https://kleber.io"
 KLEBER_API_URL="${KLEBER_URL}/api"
 KLEBER_MAX_SIZE=262144000
+KLEBER_API_KEY=0
 KLEBER_RCFILE=~/.kleberrc
 UPLOAD_LIFETIME=604800
 USERAGENT="Kleber CLI client v${VERSION}"
 DEBUG=0
+QUIET=0
 SECURE_URL=0
 EXIFTOOL=0
 API_URL=0
@@ -23,7 +25,6 @@ URL_EXT=0
 XCLIP_BIN=0
 EXIFTOOL_BIN=0
 JQ_BIN=0
-OPENSSL_BIN=0
 SCREENSHOOTER=0
 PAGINATION_OFFSET=0
 PAGINATION_LIMIT=10
@@ -32,6 +33,9 @@ trap "rm -rf ${TMPDIR}" EXIT TERM
 
 err(){
     exitval=$1
+    if [ -z $exitval ];then
+        exitval=1
+    fi
     shift
     echo 1>&2 "ERROR: $*"
     exit "$exitval"
@@ -292,10 +296,10 @@ load_config(){
 
 read_stdin() {
     local temp_file=$1
-	if tty -s; then
+    if tty -s; then
         printf "%s\n" "^C to exit, ^D to send"
-	fi
-	cat > "$temp_file"
+    fi
+    cat > "$temp_file"
 }
 
 copy_to_clipper(){
@@ -347,13 +351,13 @@ cmd_upload(){
         --dump-header $headerfile \
         ${request_url}")
     local status_code="$(cat ${headerfile} | grep -Eo '^HTTP\/1\.[0-1]\s[0-9]{3}\s' | tail -n1 | grep -Eo '[0-9]{3}')"
-    if [ -z $status_code ];then
-        err 1 "Connection to Kleber failed"
+    if [ -z "$status_code" ];then
+        err 1 "Unable to read status code"
     fi
     if [ $status_code -eq 201 ];then
         local location="$(echo ${curl_out} | jq -r .shortcut)"
         if [ -z $location ];then
-            err 1 "Could not extract location"
+            err 1 "Could not read location"
         fi
         local upload_url="${KLEBER_URL}/${location}"
         if [ -n "$UPLOAD_PASSWORD" ];then
@@ -409,7 +413,8 @@ cmd_delete(){
 }
 
 cmd_remove_meta(){
-    # A very simple exiftool wrapper that removes all metadata it knows.
+    # A very simple exiftool wrapper
+    # that removes all metadata it knows.
     local input=$1
     if [ -f "$input" ];then
         exiftoolL -all= "$input" >/dev/null 2>&1
@@ -429,7 +434,7 @@ cmd_remove_meta(){
 }
 
 cmd_upload_screenshot(){
-    if ! checkyesno $SCREENSHOOTER;then
+    if ! checkyesno "$SCREENSHOOTER";then
         err "import utility not found!"
     fi
     local tmpfile=$(mktemp "${TMPDIR}/cli.XXXXXX.png")
